/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import java.awt.Color;
/**
 *
 * @author PERSONAL
 */
public class PantallaServer extends javax.swing.JFrame {

    public Server srv;
    
    public PantallaServer() {
        initComponents();
    }

    public void setServer(Server srv){
        this.srv = srv;
    }
    
    public void addMessage(String msj){
        txtStatus.append(msj + "\n");
    }
    
    public void increaseConnections(){
        String num = Integer.toString(srv.contadorDeConexiones);
        lblConectados.setText(num);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStatus = new java.awt.TextArea();
        jLabel2 = new javax.swing.JLabel();
        lblConectados = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFieldVelocidadMina = new java.awt.TextField();
        txtFieldCantidadMina = new java.awt.TextField();
        txtFieldDinero = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnConfirmSettings = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1140, 800));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(txtStatus);
        txtStatus.setBounds(440, 320, 310, 340);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/StarWars.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 80, 390, 211);

        lblConectados.setBackground(new java.awt.Color(0, 0, 0));
        lblConectados.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        lblConectados.setForeground(new java.awt.Color(204, 204, 0));
        lblConectados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConectados.setText("0");
        lblConectados.setOpaque(true);
        getContentPane().add(lblConectados);
        lblConectados.setBounds(840, 360, 160, 110);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Dinero:");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 380, 160, 70);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Velocidad mina:");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 450, 190, 70);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cantidad mina:");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 520, 180, 70);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SETTINGS:");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 290, 210, 70);
        getContentPane().add(txtFieldVelocidadMina);
        txtFieldVelocidadMina.setBounds(220, 460, 120, 40);
        getContentPane().add(txtFieldCantidadMina);
        txtFieldCantidadMina.setBounds(220, 540, 120, 40);
        getContentPane().add(txtFieldDinero);
        txtFieldDinero.setBounds(200, 390, 120, 40);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Players Connected:");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(840, 290, 160, 70);

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(204, 204, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(850, 490, 50, 40);

        btnConfirmSettings.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnConfirmSettings.setForeground(new java.awt.Color(204, 204, 0));
        btnConfirmSettings.setText("Set");
        btnConfirmSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSettingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmSettings);
        btnConfirmSettings.setBounds(270, 620, 80, 40);

        btnConfirm.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(204, 204, 0));
        btnConfirm.setText("Set");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm);
        btnConfirm.setBounds(910, 490, 80, 40);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 290, 330, 380);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(840, 470, 160, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondoServer.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1165, 800));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1140, 810);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        
        String cantidadTmp = jComboBox1.getSelectedItem().toString();
        int cantidad = Integer.parseInt(cantidadTmp);
        srv.setAmountPlayers = cantidad;
        btnConfirm.setForeground(Color.green);
    
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnConfirmSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnConfirmSettings;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblConectados;
    private java.awt.TextField txtFieldCantidadMina;
    private java.awt.TextField txtFieldDinero;
    private java.awt.TextField txtFieldVelocidadMina;
    private java.awt.TextArea txtStatus;
    // End of variables declaration//GEN-END:variables
}
