/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

/**
 *
 * @author PERSONAL
 */
public class PantallaCliente extends javax.swing.JFrame {

    
    public Cliente refCliente;
    String nombreTurno;
    
    public PantallaCliente() {
        initComponents();
        nombreTurno = ""; 
    }
    
   public void setCliente(Cliente refCliente){
        this.refCliente = refCliente;
    }
    
    public void setNombreTurno(String player){
        this.nombreTurno = player;
    }
    
    public void pintarTurno(String player){
        this.nombreTurno = player;
      //lblTurnoPlayer.setText(player);
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNextPlayer = new javax.swing.JButton();
        txtAreaConsola = new java.awt.TextArea();
        txtFieldConsola = new java.awt.TextField();
        btnSend = new javax.swing.JButton();
        lblPlayerName1 = new javax.swing.JLabel();
        lblPlayerName2 = new javax.swing.JLabel();
        lblPlayerName3 = new javax.swing.JLabel();
        lblPlayerName4 = new javax.swing.JLabel();
        lblPlayerEnemyName = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        jPanelPropio = new javax.swing.JPanel();
        jPanelEnemigos = new javax.swing.JPanel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 950));
        setPreferredSize(new java.awt.Dimension(1444, 950));
        getContentPane().setLayout(null);

        btnNextPlayer.setText("Next");
        getContentPane().add(btnNextPlayer);
        btnNextPlayer.setBounds(1170, 50, 90, 40);
        getContentPane().add(txtAreaConsola);
        txtAreaConsola.setBounds(140, 640, 1150, 230);
        getContentPane().add(txtFieldConsola);
        txtFieldConsola.setBounds(140, 870, 1080, 30);

        btnSend.setText("Send");
        getContentPane().add(btnSend);
        btnSend.setBounds(1220, 870, 73, 30);

        lblPlayerName1.setBackground(new java.awt.Color(255, 255, 255));
        lblPlayerName1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPlayerName1.setForeground(new java.awt.Color(0, 0, 0));
        lblPlayerName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerName1.setOpaque(true);
        getContentPane().add(lblPlayerName1);
        lblPlayerName1.setBounds(40, 330, 130, 40);

        lblPlayerName2.setBackground(new java.awt.Color(255, 255, 255));
        lblPlayerName2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPlayerName2.setForeground(new java.awt.Color(204, 204, 0));
        lblPlayerName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerName2.setText("Acero:");
        lblPlayerName2.setOpaque(true);
        getContentPane().add(lblPlayerName2);
        lblPlayerName2.setBounds(40, 290, 130, 40);

        lblPlayerName3.setBackground(new java.awt.Color(255, 255, 255));
        lblPlayerName3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPlayerName3.setForeground(new java.awt.Color(0, 0, 0));
        lblPlayerName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerName3.setOpaque(true);
        getContentPane().add(lblPlayerName3);
        lblPlayerName3.setBounds(40, 250, 130, 40);

        lblPlayerName4.setBackground(new java.awt.Color(255, 255, 255));
        lblPlayerName4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPlayerName4.setForeground(new java.awt.Color(204, 204, 0));
        lblPlayerName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerName4.setText("Dinero:");
        lblPlayerName4.setOpaque(true);
        getContentPane().add(lblPlayerName4);
        lblPlayerName4.setBounds(40, 210, 130, 40);

        lblPlayerEnemyName.setBackground(new java.awt.Color(255, 255, 255));
        lblPlayerEnemyName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPlayerEnemyName.setForeground(new java.awt.Color(204, 204, 0));
        lblPlayerEnemyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerEnemyName.setText("Enemy name");
        lblPlayerEnemyName.setOpaque(true);
        getContentPane().add(lblPlayerEnemyName);
        lblPlayerEnemyName.setBounds(920, 50, 230, 40);

        lblPlayerName.setBackground(new java.awt.Color(255, 255, 255));
        lblPlayerName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPlayerName.setForeground(new java.awt.Color(204, 204, 0));
        lblPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerName.setText("Player name");
        lblPlayerName.setOpaque(true);
        getContentPane().add(lblPlayerName);
        lblPlayerName.setBounds(350, 50, 230, 40);

        jPanelPropio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanelPropio.setOpaque(false);

        javax.swing.GroupLayout jPanelPropioLayout = new javax.swing.GroupLayout(jPanelPropio);
        jPanelPropio.setLayout(jPanelPropioLayout);
        jPanelPropioLayout.setHorizontalGroup(
            jPanelPropioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanelPropioLayout.setVerticalGroup(
            jPanelPropioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelPropio);
        jPanelPropio.setBounds(210, 110, 500, 500);

        jPanelEnemigos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanelEnemigos.setOpaque(false);

        javax.swing.GroupLayout jPanelEnemigosLayout = new javax.swing.GroupLayout(jPanelEnemigos);
        jPanelEnemigos.setLayout(jPanelEnemigosLayout);
        jPanelEnemigosLayout.setHorizontalGroup(
            jPanelEnemigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanelEnemigosLayout.setVerticalGroup(
            jPanelEnemigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelEnemigos);
        jPanelEnemigos.setBounds(790, 110, 500, 500);

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ClientFondo.jpg"))); // NOI18N
        lblfondo.setMaximumSize(new java.awt.Dimension(1345, 817));
        lblfondo.setMinimumSize(new java.awt.Dimension(1345, 817));
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, 0, 1440, 930);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextPlayer;
    private javax.swing.JButton btnSend;
    private javax.swing.JPanel jPanelEnemigos;
    private javax.swing.JPanel jPanelPropio;
    private javax.swing.JLabel lblPlayerEnemyName;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPlayerName1;
    private javax.swing.JLabel lblPlayerName2;
    private javax.swing.JLabel lblPlayerName3;
    private javax.swing.JLabel lblPlayerName4;
    private javax.swing.JLabel lblfondo;
    private java.awt.TextArea txtAreaConsola;
    private java.awt.TextField txtFieldConsola;
    // End of variables declaration//GEN-END:variables
}
